### ISSUE TITLE
Extraction of the data for Fermi Surface Plot

### ISSUE THREAD

**Issue by Gargee-123** [QuantumMaterialsModelling/bands4vasp#10]
Dear Developers, 

I need to ask something regarding extraction of the data after we get the Fermi Surface plot or band structure plot. 
I have checked from the '**bands4vasp_data**' and found **Fermisurface.specfun.pm3d.dat**,  Can I use it for doing replotting ?(for color change and improve the quality of the figure)

I shall be grateful if you also mention what are '**Fermisurface.dat**' and '**Fermisurface.specfun.dat'** ?

For the unfolded bands, after generating the spectral function, we have **banddata.specfun** , Is it the correct file to replot the unfolded bands ? Also the high-symmetry points are mentioned in "**KPOINTgrid**" file , is it correct ?

Kind regards
Gargee

**Comment by MicheleReticcioli** [comment]
Dear Gargee,
yes, you are right all the way. You can use any *.dat file to generate your own plots.
Specifically, the Fermisurface.specfun.pm3d.dat file contains data on the  spectral function at the Fermi surface, formatted in the pm3d gnuplot format, while the Fermisurface.specfun.dat contains the same information, in plain format. Finally, the Fermisurface.dat file contains the information of the Fermi surface, again in plain format.

As further recommendation, it might help having a look at the *.gnu files, to get better insights.

Best,
Michele
