### ISSUE TITLE
is bands4vasp compatible with hybrid functional or metagga functional's bandstructure? is there a plan to incorporate bands4vasp in main package of VASP instead of patch??

### ISSUE THREAD

**Issue by alpinnovianus** [QuantumMaterialsModelling/bands4vasp#11]
hello,

is bands4vasp compatible with hybrid functional or metagga functional's bandstructure? 
also, is there a plan to incorporate bands4vasp in the standard VASP code instead of using patch in the future?

regards,
alpin

**Comment by MicheleReticcioli** [comment]
Hi!

Yes, it is definitely possible to use bands4vasp with hybrid/metaGGA functionals (it has been used already in couple of published papers). All you need is to follow the standard procedure to calculate band structure with hybrid/metaGGA functionals (see VASP manual); then, in the bands4vasp post-processing you can set SKIPKPOINT to skip the k-point used for the self consistence (see bands4asp documentation).

Regarding your second question, hopefully yes, but at the moment only the patch is provided.

Best,
Michele
