### ISSUE TITLE
error when start projection on the fermisurface

### ISSUE THREAD

**Issue by zrqustc** [QuantumMaterialsModelling/bands4vasp#13]
Dear band4vasp developers,

I am trying to get the unfolded fermi surface using b4vasp. But I met the following errors when I use this code.
Do you have any suggestions about this error?

                 

reading PROCAR[.prim] file(s)
100%  [||||||||||||||||||||||||||||||||||||||||||||||||||]

The following orbital(s) do not have values above 0.01 for spin=1 :
dyz , dxz , x2-y2

The following orbital(s) do not have values above 0.01 for spin=2 :
dyz , dxz , x2-y2

          write spectral function for fermisurface
100%  [||||||||||||||||||||||||||||||||||||||||||||||||||]

*********************** Spin = 1 *************************
                   looking for fermiroots
100%  [||||||||||||||||||||||||||||||||||||||||||||||||||]

  188 Fermiroots found and printed in FERMIROOTS.spin1.dat

            start projection on the fermisurface
100%  [||||||||||||||||||||||||||||||||||||||||||||||||||]

The following orbital(s) do not have values above 0.01
at the Fermi surface for spin=1:
dyz , dxz , x2-y2

**********************************************************

*********************** Spin = 2 *************************
                   looking for fermiroots
100%  [||||||||||||||||||||||||||||||||||||||||||||||||||]

  184 Fermiroots found and printed in FERMIROOTS.spin2.dat

            start projection on the fermisurface
 50%  [|||||||||||||||||||||||||                         ]double free or corruption (!prev)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x154794a3fd6f in ???
#1  0x154794a3fcdb in ???
#2  0x154794a41374 in ???
#3  0x154794a85b06 in ???
#4  0x154794a8db89 in ???
#5  0x154794a8fa1b in ???
#6  0x407f86 in ???
#7  0x41a3b4 in ???
#8  0x44d1df in ebs_main
	at /global/homes/r/rqzhang/bands4vasp/src/ebs_main.f90:149
#9  0x44d5da in main
	at /global/homes/r/rqzhang/bands4vasp/src/ebs_main.f90:2

**Comment by MicheleReticcioli** [comment]
Dear Ruiqi,
it seems to work alright for the spin channel. I do not know why it wouldn't work for the other spin channel.
The Spectral Function seems to have worked successfully as well: have you tried to plot the Fermi Surface from the Spectral Function and check if it works as expected?

**Comment by zrqustc** [comment]
Thanks for your reply. I only got the data of spectral function for ISPIN=1. I can use that data to plot the fermi surface, which makes sense to me. But for another spin channel, I can not get the data. 

Best,
Ruiqi

**Comment by MicheleReticcioli** [comment]
OK, is the PROCAR.prim printed till the end? This file contains two blocks (the first one for spin channel 1, and the second for the spin channel 2). Considering also the other issue you reported ("writing procar \n forrtl: severe (153): allocatable array or pointer is not allocated") I suspect the PROCAR.prim might be corrupted. To check whether this file was printed successfully, you could look at the numbers of NBANDS and KPOINTS, and check if the last section is indeed printed for the last k-point and last band.
