### ISSUE TITLE
problem in calculation of unfolded fermi surface

### ISSUE THREAD

**Issue by someshb1** [QuantumMaterialsModelling/bands4vasp#14]
Dear band4vasp developers,

I am trying to get the unfolded fermi surface. While I tried to prepare vasp files for the calculation using "b4vasp --pre-circle" command, multiple sub folders are created inside each folders.
├── 1cir
│   ├── band4vasp_emptyKPOINTS
│   ├── band4vasp_KPOINTScoordinates
│   ├── fermicircle4VASP.dat
│   └── KPOINTS
├── 2cir
│   ├── 1cir
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   └── KPOINTS
│   ├── band4vasp_emptyKPOINTS
│   ├── band4vasp_KPOINTScoordinates
│   ├── fermicircle4VASP.dat
│   └── KPOINTS
├── 3cir
│   ├── 1cir
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   └── KPOINTS
│   ├── 2cir
│   │   ├── 1cir
│   │   │   ├── band4vasp_emptyKPOINTS
│   │   │   ├── band4vasp_KPOINTScoordinates
│   │   │   ├── fermicircle4VASP.dat
│   │   │   └── KPOINTS
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   └── KPOINTS
│   ├── band4vasp_emptyKPOINTS
│   ├── band4vasp_KPOINTScoordinates
│   ├── fermicircle4VASP.dat
│   ├── KPOINTS
│   └── POSCAR
├── 4cir
│   ├── 1cir
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   └── KPOINTS
│   ├── 2cir
│   │   ├── 1cir
│   │   │   ├── band4vasp_emptyKPOINTS
│   │   │   ├── band4vasp_KPOINTScoordinates
│   │   │   ├── fermicircle4VASP.dat
│   │   │   └── KPOINTS
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   └── KPOINTS
│   ├── 3cir
│   │   ├── 1cir
│   │   │   ├── band4vasp_emptyKPOINTS
│   │   │   ├── band4vasp_KPOINTScoordinates
│   │   │   ├── fermicircle4VASP.dat
│   │   │   └── KPOINTS
│   │   ├── 2cir
│   │   │   ├── 1cir
│   │   │   │   ├── band4vasp_emptyKPOINTS
│   │   │   │   ├── band4vasp_KPOINTScoordinates
│   │   │   │   ├── fermicircle4VASP.dat
│   │   │   │   └── KPOINTS
│   │   │   ├── band4vasp_emptyKPOINTS
│   │   │   ├── band4vasp_KPOINTScoordinates
│   │   │   ├── fermicircle4VASP.dat
│   │   │   └── KPOINTS
│   │   ├── band4vasp_emptyKPOINTS
│   │   ├── band4vasp_KPOINTScoordinates
│   │   ├── fermicircle4VASP.dat
│   │   ├── KPOINTS
│   │   └── POSCAR
│   ├── band4vasp_emptyKPOINTS
│   ├── band4vasp_KPOINTScoordinates
│   ├── fermicircle4VASP.dat
│   ├── KPOINTS
│   └── POSCAR
├── KPOINTS
└── POSCAR

**Comment by MicheleReticcioli** [comment]
Thanks for reporting this issue. 
Could you please also report the command you used (especially the "pre-circles" command) and the KPOINTS file that you set up.
Thanks,
Michele

**Comment by someshb1** [comment]
This is the command I used
"b4vasp --pre-circle ./ 4 cir"
KPOINTS file
------
K-circle
40
rec
#makepath
0.0 0.0 0.0
0.25 0.25 0.25
0.0 0.0 0.5
--------
I have gone through the manual and tutorial for calculation of effective band structure and it is nice and clear. But I could not fully understand the steps involved in doing fermisurface calculation. Could you please elaborate this part ? 
Thank you.

**Comment by MicheleReticcioli** [comment]
The problem comes from the "./" argument. 
Please put all the VASP files in a separate folder (e.g., inputs) and run the same command but avoid to use "./", for example:
b4vasp --pre-circles inputs 4 cir

Regarding the Fermi surface, I am happy to help in case you have specific questions. In this case, please post them in a separate thread. 

Best
Michele
