### ISSUE TITLE
Problem in Unfolding of Fermisurface

### ISSUE THREAD

**Issue by someshb1** [QuantumMaterialsModelling/bands4vasp#15]
Dear b4vasp developers,

Can you please share the kpoints file and the pre-circle command used to generate the folders present in the 'b4vasp_Fermisurface_Example' directory ? It would be better if you provide step by step guidance to get 3D fermisurface.

Thank You

**Comment by MicheleReticcioli** [comment]
The 3D Fermisurface is obtained by calculating 2D Fermi surface on various planes, parallel to each other. The output data (e.g., the Fermi vectors with Bloch character as color) can then be plot by using several graphical packages (we used gnuplot). Unfortunately, we do not have the files you request available.

**Comment by MicheleReticcioli** [comment]
By simply plotting together several 2D Fermi surfaces on stacking planes, you will get an image similar to Fig. 8a in the Tutorial documentation (version Dec. 2021).
If you want to obtain a continuous mesh as in Fig. 8d, then you need to further post process the b4vasp output (manually or, perhaps, with additional software): the goal is to collect all points (at any kx, ky, kz coordinate) which belong to the same surface, and create a surface map for every group of points.

**Comment by someshb1** [comment]
Thank you very much...
