### ISSUE TITLE
Fermi Surface Unfolding

### ISSUE THREAD

**Issue by Gargee-123** [QuantumMaterialsModelling/bands4vasp#2]
Hi, 

1) Is it possible tom do Fermi Surface unfolding using b4vasp ? 
2) Can one get the Iso-surface for other energy cuts than Fermi level ?
3) Is the b4vasp works only with the VASP 6.0 or higher version ?

Thanks
Gargee

**Comment by Gargee-123** [comment]
Hi, 

I would like to inform regarding my calculation. I am trying to do Fermi surface unfolding, and therefore, I have submitted VASP job using VASP 6.2.1. I have a composite system and I am trying to do the Fermi surface unfolding of the composite system onto the BZ of one of the subsystems. 
The INCAR I have used is shown below: 

ISTART     = 1
ICHARG     = 11
IBRION     = -1
ISMEAR     = 0
EDIFF      = 1.0E-6
EDIFFG     = -0.01
ENCUT      = 500
SIGMA      = 0.01
NPAR       = 1
NSW        = 0
PREC       = Accurate
LWAVE      = .TRUE.
LCHARG     = .TRUE.
IVDW       = 11
LKPROJ     = .TRUE.
NBANDS     = 1200

I have used the same effective K path which I can use for band unfolding (as it is mentioned that we should provide K vectors). 

K-points
XX
line mode
reciprocal
X  X  X
X  X  X

X  X  X
X  X  X

X  X  X
X  X  X


I have seen that no PRJCAR file is generated. I have provided the POSCAR as the total composite structure and the POSCAR.prim as the unit cell POSCAR of one of the subsystems. 

I have also tried with another K path file as follows: 

K-points
15
P
line
rec
0.000000  0.000000  0.000000 ! Gamma
0.333333  0.333333  0.000000 ! K

0.333333  0.333333  0.000000 ! K
0.500000  0.000000  0.000000 ! M

0.500000  0.000000  0.000000 ! M
0.000000  0.000000  0.000000 ! Gamma

However, my job is getting killed with the error : 

**Error reading KPOINTS file.                                             |
|     The error occurred at line: 4.**







Alternatively I have also submitted another job with INCAR
ISTART     = 0
ICHARG     = 2
IBRION     = 2
ISMEAR     = 0
ISIF       = 3
EDIFF      = 1.0E-6
EDIFFG     = -0.01
ENCUT      = 500
SIGMA      = 0.01
NPAR       = 1
NSW        = 300
PREC       = Accurate
LWAVE      = .TRUE.
LCHARG     = .TRUE.
IVDW       = 11
LKPROJ     = .TRUE.

In this case I have used K points as : K-points
 0
G
  2  8  2
  0  0  0




I shall be grateful if you can inform me whether my calculation approach is wrong for unfolding and for Fermi surface unfolding. 

Looking forward for your helpful suggestions. 


Regards
Gargee

**Comment by MicheleReticcioli** [comment]
Dear Gargee, I didn't notice that your messages where also on this forum. Let me reply again to you, as the answer might be helpful for other people as well.
In order to use bands4vasp, you the VASP version 6.2.1 updated with the patch package that you can find at
https://github.com/QuantumMaterialsModelling/UnfoldingPatch4vasp
Enjoy,
Michele

**Comment by Gargee-123** [comment]
Dear Michele, 

Thank you for you message. Previously used older version of VASP. But I will do the Fermi Surface calculation soon with the new patch version. 

Best, 
Gargee
