### ISSUE TITLE
Plotting range for band unfolding

### ISSUE THREAD

**Issue by Gargee-123** [QuantumMaterialsModelling/bands4vasp#3]
Dear bands4vasp Developers, 

Thank you for the band unfolding code. I have used bands4vasp for band unfolding. I would like know how can I choose the energy range for band unfolding plot. My present plot only shows energy range from -0.6 to 0.6. I would like to see from -2 to 2. 
Also, I would like to show the high symmetry points Gamma, K , M in the x-axis. 

Please provide your helpful suggestion in this regard.

Best regards
Gargee

**Comment by MicheleReticcioli** [comment]
Dear Gargee,

thank you again for your interest.

You can find valuable explanations to your questions in the 
documantation of b4vasp, especially in the tutorial:
https://github.com/QuantumMaterialsModelling/bands4vasp/blob/main/bands4vasp_tutorial.pdf

Enjoy,
Michele

---
--
Dr. Michele Reticcioli
University of Vienna
Computational Materials Physics
Kolingasse 14-16 (top 3.66), A-1090 Vienna, Austria
phone: +431427773317

**Comment by Gargee-123** [comment]
Dear Michele, 

Thank you. 

Best, 
Gargee
