### ISSUE TITLE
Atom and Orbital Resolved Band Unfolding

### ISSUE THREAD

**Issue by Gargee-123** [QuantumMaterialsModelling/bands4vasp#7]
Dear Developers, 

I need to ask one question regarding the orbital resolved unfolded bands. 
The orbital resolved results that we get, that is the total orbital contribution ?
For example, I am attaching one of my results (NbSe2 system) orbital resolved unfolded bands. This is total orbital contribution from both the atoms Nb and Se, is it correct ?

![EBSorbit_ALL](https://user-images.githubusercontent.com/88433236/147347140-f3369f92-c986-4ae1-8003-47026bdc6ab4.png)

Is it also possible to get individual atomic contribution / orbital contribution from the unfolded bands ?

Best regards
Gargee

**Comment by Gargee-123** [comment]
Dear Developers, 

I need to plot the orbital resolved unfolded bands for each type of the atoms in a system. 
For example, I need all the s, px, py, pz, dxy, dyz, dz2, dxz and dx2-y2 for Nb and Se atom separately (in context of the above plot). If there is any way to get individual ion's orbital contributions, then it can be possible to sum the ions that I need to see total contribution of the ions of one type of atom. 

Best regards
Gargee

**Comment by MicheleReticcioli** [comment]
Dear Gargee,
you can decide which atoms to include with the SELECTION option in the INPAR.
Usage is described in the deafult INPAR file (all ions selected by setting the value to 0).
Best,
Michele
