### ISSUE TITLE
2D Fermi Surface Unfolded on Plane waves

### ISSUE THREAD

**Issue by Gargee-123** [QuantumMaterialsModelling/bands4vasp#8]
Dear David, 

I have a question regarding Fermi Surface Unfolding. I have a rectangular supercell of NbSe2 system and I have done the unfolded Fermi Surface of the NbSe2 supercell on NbSe2 primitive cell BZ. I have also done the Fermi Surface unfolding of NbSe2 supercell on BiSe primitive cell BZ. 

Similar way, I have rectangular BiSe supercell and I have done Fermi Surface unfolding of the BiSe supercell on BiSe primitive cell BZ and also unfolded it on NbSe2 unit cell BZ and naturally they would look different. I wanted to ask how can I compare the FS result with the actual Fermi Surface from experimental result ? 
Unfolding of any of the supercell on NbSe2 or BiSe gives different result as it is projection of supercell states onto the states of the primitive cell, it is not projected on plane waves. 

In the paper (equation 2), the projection is folded on the first BZ of the small primitive cell and therefore summation of {g} is used in the equation. Is it possible that we can get the unfolded states before folding onto the first BZ of the small cell ?
Can I directly use it from any tag in INPAR ? 

If it is not possible, it will be helpful if you guide me how can I find those Fourier coefficient from the VASP calculation, before folding back to primitive cell BZ ?
.
In the present version, the plot includes the sum over {g} and putting in the first BZ of the unit cell specified, it is possible to omit the sum over {g} in some ways ?

I have attached my result here. Looking for your helpful suggestion in this matter. 

[2D Fermi Surface.pdf](https://github.com/QuantumMaterialsModelling/bands4vasp/files/7881338/2D.Fermi.Surface.pdf)

Best regards
Gargee

**Comment by MicheleReticcioli** [comment]
Dear Gargee,
unfortunately, this is not possible with the current implementation. 
You would need to look into the code for the matrix "kappa".
Good luck,
Michele
